import time
print("Loading...")
time.sleep(5)
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
import pyfiglet
from termcolor import colored

ascii_banner = pyfiglet.figlet_format("CPS premium")
print(ascii_banner)
print(" ")
print(" ")
print("Welcome!")
time.sleep(3)
print("Starting plan selection")
time.sleep(15)
print("DONE!")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
text = colored("Please select the plan you would like to $BUY$", "blue")
print(text)
text = colored("The text you type is case sensitive. Type it correctly!.", "red")
print(text)
print(" ")
print(" ")
print("[->]Yearly Plan")
print("or")
print("[->]Monthly plan")
choice = input("")

if choice == "yearly plan":
    text = colored("you have choosen our Yearly Plan ", "green")
    print(text)
    time.sleep(1)
    text = colored("Loading...", "red")
    print(text)
    from subprocess import call
    call(["python", "Yearly.py"])

if choice == "monthly plan":
    text = colored("you have choosen our Monthly Plan ", "green")
    time.sleep(1)
    text = colored("Loading...", "red")
    print(text)
    from subprocess import call
    call(["python", "Monthly.py"])



print("error")
